import Header from "@/components/Header";
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="flex h-screen flex-col">
            <Header />
            <div
              className="flex flex-grow flex-col gap-3 overflow-y-auto p-2"
              id="content-container"
            >
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
